services:
  app:
    image: urlshortener:1
    restart: no
    container_name: urlshortener
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
    ports:
      - '8888:8080'